"""accounts: league owner and player claims

Adds ownership to leagues and claimable slots to players, then backfills every existing
league to the local owner.

The backfill is the point. A NULL owner has to mean something, and the only two candidates
are "anyone may edit this league" -- which is the hole accounts exist to close -- and "no
one may", which would strand the seasons already in the database. Assigning them to the
local identity means the app keeps working exactly as it did, and a hosted deployment can
reassign them to a real account.

Player slots are deliberately left unclaimed: those are different real people, and each
claims their own. Until then the league creator acts for them, which is what the single
-laptop draft already does.

Revision ID: 1dc80faa982d
Revises: e214149204d4
Create Date: 2026-08-21 14:48:01.462197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc80faa982d'
down_revision: Union[str, Sequence[str], None] = 'e214149204d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_leagues_owner_user_id'), ['owner_user_id'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_claim_per_league', ['league_id', 'user_id'])

    # ### end Alembic commands ###

    # Hardcoded rather than imported from app.auth.LOCAL_USER_ID: a migration is a frozen
    # record of one schema change and must not shift when application constants do.
    op.execute("UPDATE leagues SET owner_user_id = 'local' WHERE owner_user_id IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('uq_claim_per_league', type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_owner_user_id'))
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
