"""add entries.poster_path

Adds the film artwork path to a roster entry, so a standings page can show
posters without calling TMDB on every render.

Revision ID: 36f0b8f8d865
Revises:
Create Date: 2026-08-20 21:57:30.396059

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36f0b8f8d865'
down_revision: Union[str, Sequence[str], None] = '748451d55a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###
