"""initial schema

Creates the four tables. Everything before this was an ALTER against tables that no
migration had ever created -- the schema only existed because init_db() calls create_all()
at startup, so `alembic upgrade head` on an empty database failed on the first revision
with "no such table: entries". A fresh Postgres could not be provisioned at all.

Deliberately the schema as it stood BEFORE the six migrations that follow, not the current
one, so those still apply exactly as they did.

Revision ID: 748451d55a5d
Revises: 
Create Date: 2026-08-22 11:26:23.742404

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '748451d55a5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('draft_order', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('setup', 'drafting', 'complete')", name='ck_league_status'),
    sa.CheckConstraint('rounds >= 1 AND rounds <= 30', name='ck_league_rounds'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', name='uq_player_per_league')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('imdb', sa.Float(), nullable=True),
    sa.Column('letterboxd', sa.Float(), nullable=True),
    sa.Column('rt_crit', sa.Float(), nullable=True),
    sa.Column('rt_aud', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('bo_rank', sa.Integer(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=False),
    sa.Column('financial_score', sa.Float(), nullable=False),
    sa.Column('penalties', sa.Float(), nullable=False),
    sa.Column('penalty_notes', sa.Text(), nullable=False),
    sa.Column('watch_points', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', 'round', name='uq_slot_per_player'),
    sa.UniqueConstraint('league_id', 'tmdb_id', name='uq_film_per_league')
    )
    op.create_table('watches',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    op.drop_table('entries')
    op.drop_table('players')

    op.drop_table('leagues')
    # ### end Alembic commands ###
