"""league visibility

Every existing league becomes private. That is the safe direction and it is not reversible
in the other one: a league exposed by accident cannot be un-seen, whereas a private league
someone wanted public is a one-click fix they will notice immediately.

Revision ID: a3be49610b96
Revises: 1dc80faa982d
Create Date: 2026-08-21 22:04:41.533675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3be49610b96'
down_revision: Union[str, Sequence[str], None] = '1dc80faa982d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False))
        batch_op.create_check_constraint('ck_league_visibility', "visibility IN ('private', 'public')")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint('ck_league_visibility', type_='check')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
