"""add pick timer to leagues

Revision ID: e214149204d4
Revises: eab1c1946d0e
Create Date: 2026-08-21 09:53:01.253291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e214149204d4'
down_revision: Union[str, Sequence[str], None] = 'eab1c1946d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(# server_default backfills existing rows; SQLite cannot add a NOT NULL column
        # without one, and every league that predates the timer should get the default.
        sa.Column('pick_seconds', sa.Integer(), nullable=False,
                  server_default='60'))
        batch_op.add_column(sa.Column('clock_started_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('clock_started_at')
        batch_op.drop_column('pick_seconds')

    # ### end Alembic commands ###
